<select id="iCountry" name="iCountry">
<option value="AF">Afghanistan</option>
<option value="AX">Åland</option>
<option value="AL">Albanië</option>
<option value="DZ">Algerije</option>
<option value="UM">Amerikaanse ondergeschikte afgelegen eilanden</option>
<option value="AS">Amerikaans-Samoa</option>
<option value="AD">Andorra</option>
<option value="AO">Angola</option>
<option value="AI">Anguilla</option>
<option value="AQ">Antarctica</option>
<option value="AG">Antigua en Barbuda</option>
<option value="AR">Argentinië</option>
<option value="AM">Armenië</option>
<option value="AW">Aruba</option>
<option value="AU">Australië</option>
<option value="AZ">Azerbeidzjan</option>
<option value="BS">Bahama's</option>
<option value="BH">Bahrein</option>
<option value="BD">Bangladesh</option>
<option value="BB">Barbados</option>
<option value="BY">Belarus</option>
<option value="BE">België</option>
<option value="BZ">Belize</option>
<option value="BJ">Benin</option>
<option value="BM">Bermuda</option>
<option value="BT">Bhutan</option>
<option value="BO">Bolivia</option>
<option value="BQ">Bonaire</option>
<option value="BA">Bosnië en Herzegovina</option>
<option value="BW">Botswana</option>
<option value="BV">Bouveteiland</option>
<option value="BR">Brazilië</option>
<option value="IO">Brits Territorium in de Indische Oceaan</option>
<option value="VG">Britse Maagdeneilanden</option>
<option value="BN">Brunei</option>
<option value="BG">Bulgarije</option>
<option value="BF">Burkina Faso</option>
<option value="BI">Burundi</option>
<option value="KH">Cambodja</option>
<option value="CA">Canada</option>
<option value="KY">Caymaneilanden</option>
<option value="CF">Centraal-Afrikaanse Republiek</option>
<option value="CL">Chili</option><option value="CN">China</option>
<option value="CX">Christmaseiland</option>
<option value="CC">Cocoseilanden</option>
<option value="CO">Colombia</option>
<option value="KM">Comoren</option>
<option value="CG">Congo-Brazzaville</option>
<option value="CD">Congo-Kinshasa</option>
<option value="CK">Cookeilanden</option>
<option value="CR">Costa Rica</option>
<option value="CU">Cuba</option>
<option value="CW">Curaçao</option>
<option value="CY">Cyprus</option>
<option value="DK">Denemarken</option>
<option value="DJ">Djibouti</option>
<option value="DM">Dominica</option>
<option value="DO">Dominicaanse Republiek</option>
<option value="DE">Duitsland</option>
<option value="EC">Ecuador</option>
<option value="EG">Egypte</option>
<option value="SV">El Salvador</option>
<option value="GQ">Equatoriaal-Guinea</option>
<option value="ER">Eritrea</option>
<option value="EE">Estland</option>
<option value="ET">Ethiopië</option>
<option value="FO">Faeröer</option>
<option value="FK">Falklandeilanden (Islas Malvinas)</option>
<option value="FJ">Fiji</option>
<option value="PH">Filipijnen</option>
<option value="FI">Finland</option>
<option value="FR">Frankrijk</option>
<option value="TF">Franse Gebieden in de zuidelijke Indische Oceaan</option>
<option value="GF">Frans-Guyana</option>
<option value="PF">Frans-Polynesië</option>
<option value="GA">Gabon</option>
<option value="GM">Gambia</option>
<option value="GE">Georgië</option>
<option value="GH">Ghana</option>
<option value="GI">Gibraltar</option>
<option value="GD">Grenada</option>
<option value="GR">Griekenland</option>
<option value="GL">Groenland</option>
<option value="GP">Guadeloupe</option>
<option value="GU">Guam</option>
<option value="GT">Guatemala</option>
<option value="GG">Guernsey</option>
<option value="GN">Guinee</option>
<option value="GW">Guinee-Bissau</option>
<option value="GY">Guyana</option>
<option value="HT">Haïti</option>
<option value="HM">Heard- en McDonaldeilanden</option>
<option value="HN">Honduras</option>
<option value="HU">Hongarije</option>
<option value="HK">Hongkong SAR</option>
<option value="IE">Ierland</option>
<option value="IS">IJsland</option>
<option value="IN">India</option>
<option value="ID">Indonesië</option>
<option value="IQ">Irak</option>
<option value="IR">Iran</option>
<option value="IM">Isle of Man</option>
<option value="IL">Israël</option>
<option value="IT">Italië</option>
<option value="JM">Jamaica</option>
<option value="SJ">Jan Mayen</option>
<option value="JP">Japan</option>
<option value="YE">Jemen</option>
<option value="JE">Jersey</option>
<option value="JO">Jordanië</option>
<option value="CV">Kaapverdië</option>
<option value="CM">Kameroen</option>
<option value="KZ">Kazachstan</option>
<option value="KE">Kenia</option>
<option value="KG">Kirgizië</option>
<option value="KI">Kiribati</option>
<option value="KW">Koeweit</option>
<option value="HR">Kroatië (Hrvatska)</option>
<option value="LA">Laos</option>
<option value="LS">Lesotho</option>
<option value="LV">Letland</option>
<option value="LB">Libanon</option>
<option value="LR">Liberia</option>
<option value="LY">Libië</option>
<option value="LI">Liechtenstein</option>
<option value="LT">Litouwen</option>
<option value="LU">Luxemburg</option
><option value="VI">Maagdeneilanden (VS)</option>
<option value="MO">Macau SAR</option>
<option value="MK">Macedonië, Voormalige Joegoslavische Republiek</option>
<option value="MG">Madagaskar</option>
<option value="MW">Malawi</option>
<option value="MV">Maldiven</option>
<option value="MY">Maleisië</option>
<option value="ML">Mali</option>
<option value="MT">Malta</option>
<option value="MA">Marokko</option>
<option value="MH">Marshalleilanden</option>
<option value="MQ">Martinique</option>
<option value="MR">Mauritanië</option>
<option value="MU">Mauritius</option>
<option value="YT">Mayotte</option>
<option value="MX">Mexico</option>
<option value="FM">Micronesia</option>
<option value="MD">Moldavië</option>
<option value="MC">Monaco</option>
<option value="MN">Mongolië</option>
<option value="ME">Montenegro</option>
<option value="MS">Montserrat</option>
<option value="MZ">Mozambique</option>
<option value="MM">Myanmar</option>
<option value="NA">Namibië</option>
<option value="NR">Nauru</option>
<option value="NL" selected="">Nederland</option>
<option value="NP">Nepal</option>
<option value="NI">Nicaragua</option>
<option value="NC">Nieuw-Caledonië</option>
<option value="NZ">Nieuw-Zeeland</option>
<option value="NE">Niger</option>
<option value="NG">Nigeria</option>
<option value="NU">Niue</option>
<option value="MP">Noordelijke Marianen</option>
<option value="KP">Noord-Korea</option>
<option value="NO">Noorwegen</option>
<option value="NF">Norfolkeiland</option>
<option value="UA">Oekraïne</option>
<option value="UZ">Oezbekistan</option>
<option value="OM">Oman</option>
<option value="AT">Oostenrijk</option>
<option value="PK">Pakistan</option>
<option value="PW">Palau</option>
<option value="PS">Palestijnse Autoriteit</option>
<option value="PA">Panama</option>
<option value="PG">Papoea-Nieuw-Guinea</option>
<option value="PY">Paraguay</option>
<option value="PE">Peru</option>
<option value="PN">Pitcairneilanden</option>
<option value="PL">Polen</option>
<option value="PR">Porto Rico</option>
<option value="PT">Portugal</option>
<option value="QA">Qatar</option>
<option value="CI">Republiek Ivoorkust (Côte d’Ivoire)</option>
<option value="RE">Réunion</option>
<option value="RO">Roemenië</option>
<option value="RU">Rusland</option>
<option value="RW">Rwanda</option>
<option value="XS">Saba</option>
<option value="BL">Saint-Barthélemy</option>
<option value="MF">Saint-Martin</option>
<option value="SB">Salomonseilanden</option>
<option value="WS">Samoa</option>
<option value="SM">San Marino</option>
<option value="ST">São Tomé en Príncipe</option>
<option value="SA">Saudi-Arabië</option>
<option value="SN">Senegal</option>
<option value="RS">Servië</option>
<option value="SC">Seychellen</option>
<option value="SL">Sierra Leone</option>
<option value="SG">Singapore</option>
<option value="XE">Sint Eustatius</option>
<option value="SX">Sint Maarten</option>
<option value="SH">Sint-Helena</option>
<option value="SI">Slovenië</option>
<option value="SK">Slowakije</option>
<option value="SO">Somalië</option>
<option value="ES">Spanje</option>
<option value="LK">Sri Lanka</option>
<option value="KN">St. Kitts en Nevis</option>
<option value="LC">St. Lucia</option>
<option value="PM">St. Pierre en Miquelon</option>
<option value="VC">St. Vincent en de Grenadines</option>
<option value="SD">Sudan</option>
<option value="SR">Suriname</option>
<option value="SZ">Swaziland</option>
<option value="SY">Syrië</option>
<option value="TJ">Tadzjikistan</option>
<option value="TW">Taiwan</option>
<option value="TZ">Tanzania</option>
<option value="TH">Thailand</option>
<option value="TL">Timor-Leste</option>
<option value="TG">Togo</option>
<option value="TK">Tokelau-eilanden</option>
<option value="TO">Tonga</option>
<option value="TT">Trinidad en Tobago</option>
<option value="TD">Tsjaad</option>
<option value="CZ">Tsjechische Republiek</option>
<option value="TN">Tunesië</option>
<option value="TR">Turkije</option>
<option value="TM">Turkmenistan</option>
<option value="TC">Turks- en Caicoseilanden</option>
<option value="TV">Tuvalu</option>
<option value="UG">Uganda</option>
<option value="UY">Uruguay</option>
<option value="VU">Vanuatu</option>
<option value="VA">Vaticaanstad</option>
<option value="VE">Venezuela</option>
<option value="UK">Verenigd Koninkrijk</option>
<option value="AE">Verenigde Arabische Emiraten</option>
<option value="US">Verenigde Staten</option>
<option value="VN">Vietnam</option>
<option value="WF">Wallis en Futuna</option>
<option value="ZM">Zambia</option>
<option value="ZW">Zimbabwe</option>
<option value="ZA">Zuid-Afrika</option>
<option value="GS">Zuid-Georgia en de Zuidelijke Sandwicheilanden</option>
<option value="KR">Zuid-Korea</option>
<option value="SE">Zweden</option>
<option value="CH">Zwitserland</option>
</select>















